- name: copy remotedebug.sh to /usr/local/bin
  copy:
    src: remotedebug.sh
    dest: /usr/local/bin/
    mode: 0755
  tags: work-os-config

# todo: doesn't work for ubuntu > 20.04
#- name: configure screen lock after 10min (screensaver)
#  shell: gsettings set org.gnome.desktop.screensaver {{ item.name }} '{{ item.value }}'
#  become_user: "{{ os_user }}"
#  loop: "{{ screenLockSettings }}"
#  tags: work-os-config

- name: configure screen lock after 10min (session)
  shell: gsettings set org.gnome.desktop.session {{ item.name }} '{{ item.value }}'
  become_user: "{{ os_user }}"
  loop: "{{ desktopSessionSettings }}"
  tags: work-os-config

- name: disable annoying cracking noise
  copy:
    src: snd-hda-intel.conf
    dest: /etc/modprobe.d/snd-hda-intel.conf
    mode: 0644
  tags: work-os-config
